import type { Notice } from "../../../types/notice.js";

type BoardId = "sub0501" | "sub0502" | "sub0506";

const BOARD_TITLES: Record<BoardId, string> = {
  sub0501: "📢 공지사항 & 뉴스",
  sub0502: "💼 취업정보",
  sub0506: "🏆 공모전 소식",
};

function formatDate(date: Date): string {
  // Format in Asia/Seoul timezone to avoid UTC conversion issues
  const formatter = new Intl.DateTimeFormat("ko-KR", {
    timeZone: "Asia/Seoul",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  });
  
  const parts = formatter.formatToParts(date);
  const year = parts.find((p) => p.type === "year")?.value ?? "";
  const month = parts.find((p) => p.type === "month")?.value ?? "";
  const day = parts.find((p) => p.type === "day")?.value ?? "";
  
  return `${year}-${month}-${day}`;
}

export function buildCauNoticeEmail(
  notices: Notice[],
  boardIdResolver: (notice: Notice) => BoardId
): { subject: string; html: string } {
  if (!notices.length) {
    return {
      subject: "[CAU Notice Bot] 최근 7일간 새로운 공지가 없습니다",
      html: `<p>최근 7일간 새로운 공지가 없습니다.</p>`,
    };
  }

  // 최신순 정렬
  const sorted = [...notices].sort(
    (a, b) => b.publishedAt.getTime() - a.publishedAt.getTime()
  );

  // 게시판별 그룹화
  const grouped: Record<BoardId, Notice[]> = {
    sub0501: [],
    sub0502: [],
    sub0506: [],
  };

  for (const notice of sorted) {
    const boardId = boardIdResolver(notice);
    grouped[boardId].push(notice);
  }

  const totalCount = notices.length;

  const sections = (Object.keys(grouped) as BoardId[])
    .filter((boardId) => grouped[boardId].length > 0)
    .map((boardId) => {
      const items = grouped[boardId]
        .map(
          (n) => `
            <li style="margin-bottom:8px;">
              <a href="${n.url}" target="_blank" style="text-decoration:none;">
                ${n.title}
              </a>
              <span style="color:#666;font-size:12px;">
                (${formatDate(n.publishedAt)})
              </span>
            </li>
          `
        )
        .join("");

      return `
        <h3 style="margin-top:24px;">${BOARD_TITLES[boardId]}</h3>
        <ul style="padding-left:16px;">
          ${items}
        </ul>
      `;
    })
    .join("");

  const html = `
    <div style="font-family:Arial, sans-serif; line-height:1.6;">
      <h2>📬 중앙대학교 소프트웨어학부 최근 공지</h2>
      <p>최근 7일간 총 <strong>${totalCount}건</strong>의 공지가 등록되었습니다.</p>
      ${sections}
      <hr style="margin-top:32px;"/>
      <p style="font-size:12px;color:#888;">
        This email was automatically generated by CAU Notice Bot.
      </p>
    </div>
  `;

  return {
    subject: `[CAU Notice Bot] 최근 7일간 공지 ${totalCount}건`,
    html,
  };
}